services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT:-3000}
        - NODE_ENV=${NODE_ENV:-production}
        - JWT_SECRET=${JWT_SECRET}
        - SQLITE_DB_PATH=${SQLITE_DB_PATH:-/app/data/sqlite.db}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
        - NEXT_PUBLIC_IS_DEBUG=${NEXT_PUBLIC_IS_DEBUG:-false}
    container_name: zustand-todo-app
    environment:
      - PORT=${PORT:-3000}
      - NODE_ENV=${NODE_ENV:-production}
      - JWT_SECRET=${JWT_SECRET}
      - SQLITE_DB_PATH=${SQLITE_DB_PATH:-/app/data/sqlite.db}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
      - NEXT_PUBLIC_IS_DEBUG=${NEXT_PUBLIC_IS_DEBUG:-false}
    ports:
      - '3335:${PORT:-3000}'
    volumes:
      - todo-data:/app/data # Persistent volume for SQLite database
    restart: always
    labels:
      - 'com.portainer.webhook.name=cicd-update'

volumes:
  todo-data:
